on: push

name: CI

jobs:
  test:
    name: UnitTests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test-ci
  build:
    name: build and push docker image
    needs: test
    if: ${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release*' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=image_tag::${GITHUB_REF#refs/*/}-${GITHUB_RUN_NUMBER}
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: steveozo/snapshot-frontend
          tags: "${{ steps.vars.outputs.image_tag }}"
  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/development' }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "handytec-dev" #Must be unique in Heroku
          heroku_email: "stevemochuk@gmail.com"
          usedocker: true
          healthcheck: "https://handytec-dev.herokuapp.com/"
  deploy-to-test:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/release*' }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "handytec-test" #Must be unique in Heroku
          heroku_email: "stevemochuk@gmail.com"
          usedocker: true
          healthcheck: "https://handytec-test.herokuapp.com/"
  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "handytec-prod" #Must be unique in Heroku
          heroku_email: "stevemochuk@gmail.com"
          usedocker: true
          healthcheck: "https://handytec-prod.herokuapp.com/"

  tag-prod-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # Fetches entire history, so we can analyze commits since last tag
          fetch-depth: 0
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.TOKEN_FOR_GITHUB }}